version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: 'test'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pgdata:/data/postgres

  api:
    build: .
    container_name: api
    entrypoint: yarn dev
    env_file:
      - .env
    ports:
      - "{PORT}:{PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    links:
      - "db"
    depends_on:
      - "db"

volumes:
  pgdata:
    driver: local