name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: installing dependencies...
        run: yarn

      - name: checking lint application...
        run: yarn lint

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: installing dependencies...
        run: yarn

      - name: testing application...
        run: yarn test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: installing dependencies...
        run: yarn

      - name: building application...
        run: yarn build
